### ISSUE TITLE
Guide/latest - broken link

### ISSUE THREAD

**Issue by KhronosWebservices** [KhronosGroup/Vulkan-Guide#233]
These is one malformed link in the guide:

**On this page https://docs.vulkan.org/guide/latest/layers.html near the top, this link:**
/data/local/debug/vulkan
**Points to:**
hhttps://cs.android.com/android/platform/superproject//android-9.0.0_r1:frameworks/native/vulkan/libvulkan/layers_extensions.cpp;l=454[returns%201],%20then%20the%20loader%20will%20look%20in%20link:https://cs.android.com/android/platform/superproject//android-9.0.0_r1:frameworks/native/vulkan/libvulkan/layers_extensions.cpp;l=67

The schema has an extra `h` (hhttps) and the URL appears to be non-existent, once the schema is corrected.

**Comment by oddhack** [comment]
Transferred from the Antora repo - this is a typo in chapters/layers.adoc ('hhttps://' instead of 'https://') and once fixed here, will propagate through to the Antora site as well. In the [github render](https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/layers.adoc) the link text just shows up as dead text rather than a broken link.
