### ISSUE TITLE
Link to references page; is that curated also?

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-Guide#3]
I noticed that what_is_vulkan.md links to https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/vulkan/resources.md#libraries

to show other 3rd party libraries/tools/resources etc. Is that resources.md at Khronosdotorg actively curated as well? Is there a reason it is in Khronosdotorg instead of being in the Vulkan Guide repository?

**Comment by KarenGhavam-lunarG** [comment]
The reason I am asking is because I was going to link to this Khronosdotorg resources page (discovered while looking at the Vulkan Guide again) and remove any resources links I have at vulkan.lunarg.com. The following items I couldn't find on this Khronosdotorg page (which I think are relevant/useful links):

Volk
gfx-rs
Zink
ANGLE
Swiftshader

**Comment by sfricke-samsung** [comment]
I guess I didn't know if we wanted the Vulkan Guide to be the curated list. I also didn't want yet another list of libraries to appear. Also figured since there was a Khronos page that linking to Khronosdotorg was the valid option.

I guess this might be a greater Khronos question if that Khronosdotorg page is still "active" and if the Guides are now a better place to move and curate it on

**Comment by KarenGhavam-lunarG** [comment]
I guess I am not proposing that the Khronosdotorg resources page be pulled into the Vulkan Guide. More curious how well the resource pages are curated from a standpoint of keeping them up to date and removing not so good resources.

I submitted a pull request to Khronosdotorg to add some items to the Vulkan resources page.

You can close this issue.

**Comment by sfricke-samsung** [comment]
ok sounds good. Ya if we can keep that page well curated I also rather just have the Guides point there. Thanks for helping with the curation @KarenGhavam-lunarG !
